model_params:
  name: 'ResnetAE'
  in_channels: 3
  latent_dim: 256
  use_bn: false

data_params:
  data_path: "/home/ML_courses/03683533_2021/nadav_ohad_dvir/celeba/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 256
  num_workers: 4
  train_size: 40000
  test_size: 1000

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  manual_seed: 42
  random_val_batch: false

trainer_params:
  accelerator: "gpu"
  devices: [0]
  max_epochs: 40

logging_params:
  save_dir: "logs/"
  name: "ResnetAE"