model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 256


data_params:
  data_path: "/home/ML_courses/03683533_2021/dataset"
  train_batch_size: 64
  val_batch_size:  16
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 42
  random_val_batch: false
  sample_size: 16

trainer_params:
  gpus: [1]
  max_epochs: 70

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"